---
title: "Aide-mémoire `SAS` - `R` - `pandas`"
lang : fr
author:
  - name: Nassab ABDALLAH
    affiliation: Dares/SD-STRP/SCS, <nassab.abdallah@travail.gouv.fr>
  - name: Damien EUZENAT
    affiliation: Dares/SD-SEPEFP/DIP, <damien.euzenat@travail.gouv.fr>
  - name: Sébastien LI-THIAO-TE
    affiliation: Dares/SD-SEPEFP/DFA, <sebastien.li-thiao-te@travail.gouv.fr>
  - name: Clotilde NIETGE
    affiliation: Dares/SD-EMT/DE, <clotilde.nietge@travail.gouv.fr>

format:
  html:
    toc: true
    toc-expand: 1
    toc-location: left
    number-sections: true
    code-copy: true
    smooth-scroll: true
    embed-resources: true
    link-external-icon:	true
    link-external-newwindow: true
    page-layout: full
    code-tools: true
# format : native   
editor: source
execute:
  eval: false

embed-resources: true

syntax-definitions: 
  - sas.xml

# Summary for listings and search engines
description: |
  Un aide-mémoire pour les statisticiens traduisant des codes standards en `SAS`, en `R`, suivant 4 environnements (`R base`, `tidyverse`, `data.table`, `arrow/duckdb`) et en `python pandas`.

# Date published
date: "`r Sys.Date()`"

output:
  rmdformats::robobook:
    highlight: tango
    number_sections: true

categories:
  - SAS
  - R
  - Pandas
---

L'aide-mémoire a pour but de fournir des codes écrits en `SAS` et d'en donner la traduction en différents environnements `R` :

-   `R base`

-   `tidyverse`

-   `data.table`

-   `arrow/duckdb`

et en `python pandas`.

Les codes traduits sont typiques de la production statistique ou la réalisation d'études descriptives.

Ce document vise à faciliter la compréhension ou la traduction de codes ainsi que le passage d'un langage présenté à un autre. Il s'adresse notamment aux utilisateurs d'un de ces langages qui souhaitent comprendre ou traduire des codes écrits dans un autre langage.

Il se veut complémentaire de la documentation en ligne en français Utilit'R, née à l'Insee (<https://www.book.utilitr.org/>). Le lecteur est invité à s'y référer pour obtenir des informations importantes sur l'utilisation de `R` et qui ne sont pas discutées dans ce document, comme l'importation de données en `R` (<https://www.book.utilitr.org/03_fiches_thematiques/fiche_import_fichiers_plats>). 

Enfin, si vous souhaitez collaborer à cet aide-mémoire ou nous faire part de votre avis, n'hésitez pas à nous contacter via nos adresses email.


{{< include _Chapitre1.qmd >}}

{{< include _Chapitre2.qmd >}}

{{< include _Chapitre3.qmd >}}

{{< include _Chapitre4.qmd >}}

{{< include _Chapitre5.qmd >}}

{{< include _Chapitre6.qmd >}}

{{< include _Chapitre7.qmd >}}

{{< include _Chapitre8.qmd >}}

{{< include _Chapitre9.qmd >}}

{{< include _Chapitre10.qmd >}}

{{< include _Chapitre11.qmd >}}

{{< include _Chapitre12.qmd >}}

{{< include _Chapitre13.qmd >}}

{{< include _Chapitre14.qmd >}}

{{< include _Chapitre15.qmd >}}

{{< include _Chapitre16.qmd >}}

{{< include _Chapitre17.qmd >}}

{{< include _Chapitre18.qmd >}}

{{< include _Chapitre19.qmd >}}

{{< include _Chapitre20.qmd >}}

{{< include _Chapitre21.qmd >}}

{{< include _Chapitre22.qmd >}}

{{< include _Chapitre23.qmd >}}

{{< include _Chapitre24.qmd >}}

{{< include _Chapitre25.qmd >}}

{{< include _Chapitre26.qmd >}}

{{< include _Chapitre27.qmd >}}

{{< include _Chapitre28.qmd >}}
