---
title: "Mise en garde"
lang : fr
author:
  - name: Nassab ABDALLAH
    affiliation: Dares/SCS, <nassab.abdallah@travail.gouv.fr>
  - name: Damien EUZENAT
    affiliation: Dares/DIP, <damien.euzenat@travail.gouv.fr>
format:
  html:
    toc: true
    toc-expand: 2
    toc-location: left
    number-sections: true
    code-copy: true
    smooth-scroll: true
    link-external-icon:	true
    link-external-newwindow: true
    page-layout: full
    code-tools: true
    
# format : native    

editor: visual

# Summary for listings and search engines
description: |
  Comment utiliser cet aide-mémoire ?

# Date published
date: "`r Sys.Date()`"
date-format: "DD MMMM, YYYY"
date-modified: "05/24/2024"
output:
  rmdformats::robobook:
    highlight: tango
    number_sections: true
  
categories:
  - R
---

# Comment utiliser cet aide-mémoire ?

Sont présentés dans cet aide-mémoire des programmes statistiques courants pour la gestion de données statistiques, traduits dans les langages SAS et R (environnements `R-Base`, `Tidyverse` et `data.table` et `Arrow/DuckDb`). Ces tâches sont standards dans l'analyse statistique et réalisables en un petit nombre d'instructions.

Cet aide-mémoire vise à faciliter la traduction des programmes statistiques entre ces différents langages (de SAS vers R, et d'un environnement R à un autre), et leur appropriation.

Il est présenté sous forme de tâches élémentaires statistiques (sélection de lignes ou de colonnes d'une base de données, repérage des doublons, etc.).

Quatre grands environnements R sont traités : `R-Base`, `Tidyverse` et `data.table` et `Arrow/DuckDb`). Ils ne doivent pas être vus comme des concurrents, mais comme des compléments :

-   certaines tâches peuvent être plus ou moins facilement réalisées avec l'un ou l'autre ;
-   ils présentent chacun des avantages et des inconvénients ;
-   ils laissent le choix de la stratégie de codage.

Ce guide est destiné à vous permettre de jongler plus facilement entre les environnements.

Plusieurs solutions pour réaliser la même tâche sont proposées dans ce guide :

-   certaines solutions peuvent être plus concises, mais moins claires ;
-   d'autres plus ou moins rapides en fonction des données et des matériels et logiciels utilisés ;
-   certaines façons de procéder sont plus efficaces que d'autres en R, mais cela peut dépendre des données et du matériel utilisé.

L'attention du lecteur est attirée sur le fait que :

1)  ce guide n'est pas exhaustif. Ainsi, les environnements peuvent proposer des solutions *ad-hoc* simplifiant grandement la résolution de problèmes moins courants et qui ne sont pas présents dans les autres environnements (ex. des *rolling joins* de data.table) ;

2)  ce guide ne traite pas de ces stratégies, et le lecteur est invité à se documenter sur les environnements pour en savoir plus ;

3)  l'exercice de traduction de SAS vers R peut s'apparenter à la traduction d'un texte en langue étrangère. De même qu'une traduction littérale d'un texte en peut parfois être de mauvaise qualité, la traduction littérale d'une masse de codes SAS en codes R au moyen de cet aide-mémoire peut produire des résultats décevants. En effet, toute bonne traduction nécessite au moins *a minima* d'adapter le code SAS à une "nouvelle langue", celle de R. La partie sur les spécificités de SAS par rapport à R peut vous aider sur ce point.
